### ISSUE TITLE
The rdf script only creates nodes

### ISSUE THREAD

**Issue by peterolson** [rspective/semantic-network#1]
When I run `node rdf.js` it inserts a bunch of Synset nodes (about 208k of them) into the database but no relationships between them. How do I add the relationships?

**Comment by pawelrychlik** [comment]
The current version is able to process Synsets only (that's the case when `pred === 'label'` https://github.com/rspective/semantic-network/blob/master/rdf.js#L62), that's why you end up with ~200k vertices and no links between them.

I've successfully created a fully functional solution based on this foundation, with many kinds of wordnet relationships and even language translations baked in, but I don't own the code, so it's not here (yet).

In short, the key is to run the whole wordnet import process twice:
- first, you create all synsets. Here it's useful to build a map `wordnet ID => neo4j ID` as you go.
- second, you create all relationships. The code is very similar to the first step. The map will let you pick neo4j nodes corresponding to the wordnet ID, then you just `tx.relate(from, pred, to)` to create the link. You may get a few errors in this step due to missing IDs, etc.

This is basically it. Ofc, you may want to further improve error handling, logging and batch tx, especially if you use neo4j in the cloud.

**Comment by peterolson** [comment]
Great, I think I've basically figured it out now. Thanks for putting this on GitHub, it helped me get started with using WordNet in Neo4j.

**Comment by pawelrychlik** [comment]
@peterolson you're welcome :)
